### ISSUE TITLE
Test Mac Support

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyPropClient#6]

**Comment by DarkmatterVale** [comment]
I have been doing a little work on the client recently, and I found a bug. The stack trace in terminal can be seen below. I have no idea what is causing this error.

It occurs when I start the client, click connect, and then try and compile a program from BlocklyProp. This  then somehow throws an OSError: File or Directory not found

``` [29/Mar/2015:07:36:03] HTTP 
Request Headers:
  Content-Length: 121
  REFERER: http://blocklyprop.creatingfuture.eu/blocklyc.html
  HOST: localhost:6009
  ORIGIN: http://blocklyprop.creatingfuture.eu
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11
  ACCEPT-LANGUAGE: en-us
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  ACCEPT-ENCODING: gzip, deflate
[29/Mar/2015:07:36:03] HTTP Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/vtolpegin/Downloads/BlocklyPropClient-master/BlocklyServer.py", line 53, in compile
    result = self.compiler[language].handle(action, code, comport)
  File "/Users/vtolpegin/Downloads/BlocklyPropClient-master/PropCCompiler.py", line 38, in handle
    compile_success, binary_file, compile_output, compile_err = self.compile(action, code)
  File "/Users/vtolpegin/Downloads/BlocklyPropClient-master/PropCCompiler.py", line 80, in compile
    process = subprocess.Popen(executing_data, stdout=subprocess.PIPE, stderr=subprocess.PIPE)  # call compile
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

127.0.0.1 - - [29/Mar/2015:07:36:03] "POST /compile.action HTTP/1.1" 500 2493 "http://blocklyprop.creatingfuture.eu/blocklyc.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11" ```

**Comment by DarkmatterVale** [comment]
It was working when I was able to get my server working (since authentication rewrite I have been having issues).
