### ISSUE TITLE
Log location denial kills app on Mac

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyPropClient#66]
@zfi - Building the Mac today app after merging in latest Demo work produces a condition we've seen, and fixed, before... 
  - when run from the Launchpad, Finder, or Spotlight, the BlocklyPropClient app starts and then immediately stops, producing no GUI or visible error message.
  - when run from the console, it indicates that it tried to create a log file inside the Application's bundle... something only _su-privileged_ processes can do:
```
Jeffs-Mac:BlocklyPropClient.app jmartin$ /Applications/BlocklyPropClient.app/Contents/MacOS/BlocklyPropClient 
Traceback (most recent call last):
  File "<string>", line 293, in <module>
  File "<string>", line 51, in __init__
  File "BlocklyLogger.py", line 80, in init
  File "logging/__init__.py", line 913, in __init__
  File "logging/__init__.py", line 943, in _open
IOError: [Errno 13] Permission denied: '/Applications/BlocklyPropClient.app/BlocklyPropClient.log'
BlocklyPropClient returned -1

```

This is the behavior, I believe, that was fixed in [commit 2848f1cd8](https://github.com/parallaxinc/BlocklyPropClient/commit/2848f1cd8bc8b98531128bb83c702b5c8161511b), which I verified is in my branch's log history, but I'm now seeing the behavior again.

NOTE: I _just_ managed to get the Mac build to properly generate a modern application bundle format, which equates to two new subfolders in the app's path(__bolded__ below):     
  - /Applications/BlocklyPropClient.app/ __Contents/MacOS/__ BlocklyPropClient 

~Maybe the log file creation _is_ allowed inside the same folder as the actual executable?~ (see next post)  That would be inside the .../Contents/MacOS/ folder.

**Comment by PropGit** [comment]
__UPDATE__

I just updated the build spec and rebuilt, with a slightly different outcome that appears to be trying to put the log file deeper into the bundle and is also denied.  From this, I now realize that it's trying to write the log file in the folder where the call to launch the application came from, instead of to a specific folder.
```
Jeffs-Mac:MacOS jmartin$ ./BlocklyPropClient 
Traceback (most recent call last):
  File "<string>", line 293, in <module>
  File "<string>", line 51, in __init__
  File "BlocklyLogger.py", line 80, in init
  File "logging/__init__.py", line 913, in __init__
  File "logging/__init__.py", line 943, in _open
IOError: [Errno 13] Permission denied: '/Applications/BlocklyPropClient.app/Contents/MacOS/BlocklyPropClient.log'
BlocklyPropClient returned -1

```

**Comment by zfi** [comment]
The error occurs when we actually try to open the logging file. I am unsure what the logging system is trying to open the log file where the error indicates. The leading candidate is that the code is not detecting the host environment correctly. Can you rerun the client from the command line and gather the console output? 

The [Apple File System Programming Guide](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html) seems to indicate that the log file does belong within the user's local Library directory tree but perhaps not exactly where it is being placed now.

**Comment by PropGit** [comment]
Are we using __Library__ or __/Library__?  Looks like the first is what is most appropriate unless we want to share the log between users.

Okay, I re-ran producing the same terminal output as above, and this is the only console output from the "BlocklyPropClient" process:
```
default	06:54:49.817852 -0800	BlocklyPropClient	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	06:54:49.865013 -0800	BlocklyPropClient	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
```

Here's the total console output at the time:
```
default	06:54:45.776687 -0800	gamed	GKClientProxy: clientForBundleID:
default	06:54:45.777619 -0800	gamed	GKClientProxy: updateIfRecentlyInstalled
default	06:54:45.799943 -0800	gamed	GKClientProxy: clientForBundleID:
default	06:54:45.800397 -0800	gamed	GKClientProxy: updateIfRecentlyInstalled
default	06:54:45.979855 -0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	06:54:45.982762 -0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	06:54:45.983021 -0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	06:54:45.983406 -0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	06:54:45.984366 -0800	cupsd	subsystem: com.apple.securityd, category: storagemgr, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
default	06:54:45.984483 -0800	cupsd	using system preferences
default	06:54:45.984710 -0800	cupsd	subsystem: com.apple.securityd, category: secpref, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
default	06:54:45.985461 -0800	cupsd	subsystem: com.apple.securityd, category: integrity, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
default	06:54:45.985515 -0800	cupsd	not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
default	06:54:45.985538 -0800	cupsd	not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
default	06:54:47.831686 -0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	06:54:49.785138 -0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	06:54:49.793093 -0800	trustd	asynchronously fetching CRL (<CFURL 0x7f84d4c3b580 [0x7fffe4e4fc30]>{string = http://crl.apple.com/timestamp.crl, encoding = 1536, base = (null)}) for client (launchservicesd[91])
default	06:54:49.793449 -0800	trustd	asynchronously fetching CRL (<CFURL 0x7f84d4c292d0 [0x7fffe4e4fc30]>{string = http://crl.apple.com/root.crl, encoding = 1536, base = (null)}) for client (launchservicesd[91])
default	06:54:49.793626 -0800	ocspd	DbOpen of /private/var/db/crls/crlcache2.db
default	06:54:49.793829 -0800	ocspd	0x7faacd50e340 opened /private/var/db/crls/crlcache2.db: 25424 bytes
default	06:54:49.793978 -0800	ocspd	0x7faacd50e340 allocated /private/var/db/crls/crlcache2.db buffer 0x7faacd810400 size 25424
default	06:54:49.794068 -0800	ocspd	0x7faacd50e340 closed /private/var/db/crls/crlcache2.db
default	06:54:49.794896 -0800	ocspd	loading /private/var/db/crls/crlcache2.db
default	06:54:49.795175 -0800	securityd	looking for a common at /private/var/db/crls/crlcache2.db
default	06:54:49.795215 -0800	securityd	found a common for /private/var/db/crls/crlcache2.db at 0x7fb7b55272c0
default	06:54:49.795236 -0800	securityd	found 0x7fb7b55272c0
default	06:54:49.795495 -0800	ocspd	0x7faacd50e340 free /private/var/db/crls/crlcache2.db buffer 0x7faacd810400
default	06:54:49.796247 -0800	ocspd	DbOpen of /private/var/db/crls/crlcache2.db
default	06:54:49.796418 -0800	ocspd	0x7faacd429320 opened /private/var/db/crls/crlcache2.db: 25424 bytes
default	06:54:49.796538 -0800	ocspd	0x7faacd429320 allocated /private/var/db/crls/crlcache2.db buffer 0x7faace01d600 size 25424
default	06:54:49.796667 -0800	ocspd	0x7faacd429320 closed /private/var/db/crls/crlcache2.db
default	06:54:49.797788 -0800	ocspd	loading /private/var/db/crls/crlcache2.db
default	06:54:49.798592 -0800	securityd	looking for a common at /private/var/db/crls/crlcache2.db
default	06:54:49.798744 -0800	securityd	found a common for /private/var/db/crls/crlcache2.db at 0x7fb7b55272c0
default	06:54:49.798820 -0800	securityd	found 0x7fb7b55272c0
default	06:54:49.799031 -0800	ocspd	0x7faacd429320 free /private/var/db/crls/crlcache2.db buffer 0x7faace01d600
default	06:54:49.801399 -0800	trustd	cert[2]: AnchorTrusted =(leaf)[force]> <CFBoolean 0x7fffe4e505d8 [0x7fffe4e4fc30]>{value = false}
default	06:54:49.802188 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.802296 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.802367 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.802404 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.802494 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.802533 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.802574 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.802606 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.802651 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.802683 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.802726 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.802757 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.817852 -0800	BlocklyPropClient	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	06:54:49.836747 -0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	06:54:49.846702 -0800	trustd	asynchronously fetching CRL (<CFURL 0x7f84d4d2dda0 [0x7fffe4e4fc30]>{string = http://crl.apple.com/timestamp.crl, encoding = 1536, base = (null)}) for client (launchservicesd[91])
default	06:54:49.847051 -0800	trustd	asynchronously fetching CRL (<CFURL 0x7f84d4d16f50 [0x7fffe4e4fc30]>{string = http://crl.apple.com/root.crl, encoding = 1536, base = (null)}) for client (launchservicesd[91])
default	06:54:49.847246 -0800	ocspd	DbOpen of /private/var/db/crls/crlcache2.db
default	06:54:49.847424 -0800	ocspd	0x7faacd50e2b0 opened /private/var/db/crls/crlcache2.db: 25424 bytes
default	06:54:49.847471 -0800	ocspd	0x7faacd50e2b0 allocated /private/var/db/crls/crlcache2.db buffer 0x7faacd810400 size 25424
default	06:54:49.847502 -0800	ocspd	0x7faacd50e2b0 closed /private/var/db/crls/crlcache2.db
default	06:54:49.848571 -0800	ocspd	loading /private/var/db/crls/crlcache2.db
default	06:54:49.848856 -0800	securityd	looking for a common at /private/var/db/crls/crlcache2.db
default	06:54:49.848896 -0800	securityd	found a common for /private/var/db/crls/crlcache2.db at 0x7fb7b55272c0
default	06:54:49.848916 -0800	securityd	found 0x7fb7b55272c0
default	06:54:49.849190 -0800	ocspd	0x7faacd50e2b0 free /private/var/db/crls/crlcache2.db buffer 0x7faacd810400
default	06:54:49.849669 -0800	ocspd	DbOpen of /private/var/db/crls/crlcache2.db
default	06:54:49.849757 -0800	ocspd	0x7faacd50e240 opened /private/var/db/crls/crlcache2.db: 25424 bytes
default	06:54:49.849806 -0800	ocspd	0x7faacd50e240 allocated /private/var/db/crls/crlcache2.db buffer 0x7faacd810400 size 25424
default	06:54:49.849834 -0800	ocspd	0x7faacd50e240 closed /private/var/db/crls/crlcache2.db
default	06:54:49.850675 -0800	ocspd	loading /private/var/db/crls/crlcache2.db
default	06:54:49.850859 -0800	securityd	looking for a common at /private/var/db/crls/crlcache2.db
default	06:54:49.850899 -0800	securityd	found a common for /private/var/db/crls/crlcache2.db at 0x7fb7b55272c0
default	06:54:49.850919 -0800	securityd	found 0x7fb7b55272c0
default	06:54:49.851172 -0800	ocspd	0x7faacd50e240 free /private/var/db/crls/crlcache2.db buffer 0x7faacd810400
default	06:54:49.853272 -0800	trustd	cert[2]: AnchorTrusted =(leaf)[force]> <CFBoolean 0x7fffe4e505d8 [0x7fffe4e4fc30]>{value = false}
default	06:54:49.854062 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.854171 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.854242 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.854282 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.854375 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.854417 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.854463 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.854500 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.854558 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.854599 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.854644 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.854674 -0800	launchservicesd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	06:54:49.865013 -0800	BlocklyPropClient	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	06:54:50.195116 -0800	CommCenter	#I CSIAppInfo.ApplicationActivationObserver: handleLSNotitifcation_sync: Application exited: <private>
default	06:54:50.201725 -0800	CommCenter	#I CSIAppInfo.ApplicationActivationObserver: handleLSNotitifcation_sync: Application exited: <private>
default	06:54:50.207972 -0800	gamed	GKClientProxy: clientForBundleID:
default	06:54:52.030125 -0800	CommCenter	#watchdog #I Callback Watchdog: checkin 38
default	06:54:52.030317 -0800	CommCenter	#watchdog #I Server Watchdog: checkin 38
default	06:54:52.873911 -0800	gamed	GKClientProxy: clientForBundleID:
default	06:54:52.875130 -0800	gamed	GKClientProxy: updateIfRecentlyInstalled
default	06:54:52.876000 -0800	gamed	GKClientProxy: clientForBundleID:
default	06:54:52.876403 -0800	gamed	GKClientProxy: updateIfRecentlyInstalled
default	06:54:52.956807 -0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	06:54:55.133757 -0800	securityd	port 23059 is dead
default	06:54:55.133860 -0800	securityd	0x7fff5714e8d0 dead connection 23059
default	06:54:55.133894 -0800	securityd	Connection 0x7fb7b5503c30 aborted
default	06:54:55.133927 -0800	securityd	releasing client connection 0x7fb7b5503c30
```

**Comment by PropGit** [comment]
Tested on Jeff's Sierra VM (which was experiencing the problems noted above) and now it works properly regardless of where it's launched from!  Success!
